#ifndef __ISR80H_ISR80H_H
#define __ISR80H_ISR80H_H

enum SystemCommands {
	SYSTEM_COMMAND0_SUM,
	SYSTEM_COMMAND1_PRINT,
	SYSTEM_COMMAND2_GETKEY,
	SYSTEM_COMMAND3_PUTCHAR,
	SYSTEM_COMMAND4_MALLOC,
	SYSTEM_COMMAND5_FREE,
	STSTEM_COMMAND6_PROCESS_LOAD_START,
};

void isr80h_register_commands();

#endif